package Easy;
//TASK.389
//You are given two strings s and t.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Return the letter that was added to t.

import java.util.Arrays;

public class FindTheDifference {
    public static void main(String[] args) {
        String s1 = "abcd";
        String t1 = "abcde";
        System.out.println(findTheDifference(s1, t1));

        String s2 = "";
        String t2 = "y";
        System.out.println(findTheDifference(s2, t2));

        String s3 = "makeabbascol";
        String t3 = "abbasmakecool";
        System.out.println(findTheDifference(s3, t3));
    }

    private static char findTheDifference(String s, String t) {
        char [] stringS = s.toCharArray();
        char [] stringT = t.toCharArray();

        Arrays.sort(stringS);
        Arrays.sort(stringT);

        for (int i = 0; i < stringS.length; i++) {
            if(stringS[i] != stringT[i]) return stringT[i];
        }
        return stringT[stringS.length];
    }
}
